name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Grant execute permission for gradlew
        run: chmod +x ./carRent/gradlew
      - name: Build and test
        run: |
          export SHELL=/bin/bash
          cd ./carRent
          ./gradlew build